/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arbolesygrafos;

import arbolgrafico.PanelFondo;
import arbolgrafico.SimuladorArbolBinario;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Rectangle;
import java.util.logging.*;
import java.util.regex.*;
import static javafx.scene.paint.Color.color;
import static javafx.scene.paint.Color.color;
import javax.swing.JInternalFrame;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.*;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.*;

/**
 *
 * @author esau_
 */
public class Analizador extends javax.swing.JFrame {

    private Object O[];
    private SimuladorArbolBinario simulador = new SimuladorArbolBinario();
    boolean bandera;
    char b;
    int cont;
        Object aux[]=new Object[20];
        String demas="";
        
    public void subrayar(JTextArea area1, String texto) {
        if (texto.length() >= 1) {
            DefaultHighlighter.DefaultHighlightPainter highlightPainter = new DefaultHighlighter.DefaultHighlightPainter(Color.RED);
            Highlighter h = area1.getHighlighter();
            h.removeAllHighlights();
            String text = area1.getText();
            String caracteres = texto;
            Pattern p = Pattern.compile("(?i)" + caracteres);
            Matcher m = p.matcher(text);
            while (m.find()) {
                try {
                    h.addHighlight(m.start(), m.end(), highlightPainter);
                } catch (BadLocationException ex) {
                    Logger.getLogger(Color.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(area1, "<html><center><font size='+2' color='BLACK'> ERROR EN LA SINTAXIS FAVOR DE REVISAR </font></center></html>","",0);
        }
    }
    public void quitarSubrayado(JTextArea area1){
            DefaultHighlighter.DefaultHighlightPainter highlightPainter = new DefaultHighlighter.DefaultHighlightPainter(Color.RED);
            Highlighter h = area1.getHighlighter();
            h.removeAllHighlights();
       
    }

    public Analizador() {
        initComponents();
        m = (DefaultTableModel) tblToken.getModel();
        O = new Object[2];
        this.setLocationRelativeTo(null);
        setTitle("Analizador Sintactico");//Nombre ventana.
        this.inicializar(false);
        PanelFondo F = new PanelFondo();
        ArbolBoton.setEnabled(false);
        Limpiar_Boton.setEnabled(false);
        bandera=false;
        Limpiar_Boton.setVisible(false);
        cont=0;
        b=' ';
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEditor = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblToken = new javax.swing.JTable();
        pnlArbol = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        btnAnalizar = new javax.swing.JButton();
        Limpiar_Boton = new javax.swing.JButton();
        ArbolBoton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuNuevo = new javax.swing.JMenuItem();
        mnuAbrir = new javax.swing.JMenuItem();
        mnuGuardar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(26, 35, 126));

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        txtEditor.setBackground(new java.awt.Color(232, 234, 246));
        txtEditor.setColumns(20);
        txtEditor.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        txtEditor.setForeground(new java.awt.Color(26, 35, 126));
        txtEditor.setRows(5);
        txtEditor.setText("total=precio*3.5;");
        txtEditor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onClick(evt);
            }
        });
        jScrollPane1.setViewportView(txtEditor);

        tblToken.setBackground(new java.awt.Color(232, 234, 246));
        tblToken.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        tblToken.setForeground(new java.awt.Color(26, 35, 126));
        tblToken.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Token", "Tipo"
            }
        ));
        jScrollPane2.setViewportView(tblToken);

        pnlArbol.setBackground(new java.awt.Color(232, 234, 246));
        pnlArbol.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Arbol Sintactico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24), new java.awt.Color(26, 35, 126))); // NOI18N
        pnlArbol.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N

        jDesktopPane1.setOpaque(false);

        jInternalFrame2.setBackground(new java.awt.Color(255, 255, 255));
        jInternalFrame2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jInternalFrame2.setIconifiable(true);
        jInternalFrame2.setMaximizable(true);
        jInternalFrame2.setResizable(true);
        jInternalFrame2.setEnabled(false);
        jInternalFrame2.setFocusCycleRoot(false);
        jInternalFrame2.setVisible(true);

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
        );

        jDesktopPane1.add(jInternalFrame2);
        jInternalFrame2.setBounds(0, 0, 900, 410);

        javax.swing.GroupLayout pnlArbolLayout = new javax.swing.GroupLayout(pnlArbol);
        pnlArbol.setLayout(pnlArbolLayout);
        pnlArbolLayout.setHorizontalGroup(
            pnlArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 911, Short.MAX_VALUE)
            .addGroup(pnlArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlArbolLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 891, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlArbolLayout.setVerticalGroup(
            pnlArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
            .addGroup(pnlArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlArbolLayout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(117, Short.MAX_VALUE)))
        );

        btnAnalizar.setBackground(new java.awt.Color(204, 204, 204));
        btnAnalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_Search_48px.png"))); // NOI18N
        btnAnalizar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarActionPerformed(evt);
            }
        });

        Limpiar_Boton.setBackground(new java.awt.Color(204, 204, 204));
        Limpiar_Boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_Broom_65px.png"))); // NOI18N
        Limpiar_Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Limpiar_BotonActionPerformed(evt);
            }
        });

        ArbolBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_Oak_Tree_65px.png"))); // NOI18N
        ArbolBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArbolBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlArbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnAnalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(ArbolBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(Limpiar_Boton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ArbolBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAnalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(Limpiar_Boton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(pnlArbol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("Archivo");

        mnuNuevo.setText("Nuevo");
        mnuNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnumnuNuevoActionPerformed(evt);
            }
        });
        jMenu1.add(mnuNuevo);

        mnuAbrir.setText("Abrir");
        jMenu1.add(mnuAbrir);

        mnuGuardar.setText("Guardar");
        jMenu1.add(mnuGuardar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Analizar");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnumnuNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnumnuNuevoActionPerformed
     ArbolBoton.setEnabled(false);
        Limpiar_Boton.setEnabled(false);
        btnAnalizar.setEnabled(true);
        txtEditor.setText("");
        limpiaTabla();
    }//GEN-LAST:event_mnumnuNuevoActionPerformed

    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
        try {
            String dato = txtEditor.getText();
            if (this.simulador.insertar(dato)) {
                this.inicializar(true);
                analizar(dato);
                if(!bandera){
                ArbolBoton.setEnabled(true);
                Limpiar_Boton.setEnabled(true);}
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Revise La Sintaxis Por Favor");
        }
        //analizar(txtEditor.getText());
    }//GEN-LAST:event_btnAnalizarActionPerformed

    private void ArbolBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArbolBotonActionPerformed
        complementos();
    }//GEN-LAST:event_ArbolBotonActionPerformed

    private void Limpiar_BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Limpiar_BotonActionPerformed
        ArbolBoton.setEnabled(false);
        Limpiar_Boton.setEnabled(false);
        btnAnalizar.setEnabled(true);
        txtEditor.setText("");
        limpiaTabla();
        this.jDesktopPane1.removeAll();
        Rectangle tamaño = this.jInternalFrame2.getBounds();
        this.jInternalFrame2 = null;
        this.jInternalFrame2 = new JInternalFrame("Representación Fráfica", true);
        this.jDesktopPane1.add(this.jInternalFrame2, JLayeredPane.DEFAULT_LAYER);
        this.jInternalFrame2.setVisible(true);
        this.jInternalFrame2.setBounds(tamaño);
        this.jInternalFrame2.setEnabled(false);
    }//GEN-LAST:event_Limpiar_BotonActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void onClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onClick
        ArbolBoton.setEnabled(false);
        Limpiar_Boton.setEnabled(false);
        btnAnalizar.setEnabled(true);
        limpiaTabla();
        this.jDesktopPane1.removeAll();
        Rectangle tamaño = this.jInternalFrame2.getBounds();
        this.jInternalFrame2 = null;
        this.jInternalFrame2 = new JInternalFrame("Representación Fráfica", true);
        this.jDesktopPane1.add(this.jInternalFrame2, JLayeredPane.DEFAULT_LAYER);
        this.jInternalFrame2.setVisible(true);
        this.jInternalFrame2.setBounds(tamaño);
        this.jInternalFrame2.setEnabled(false);
        quitarSubrayado(txtEditor);
        txtEditor.requestFocus();
    }//GEN-LAST:event_onClick
    
    //Limpiar Tabla
    private void limpiaTabla(){
        try{
            DefaultTableModel temp = (DefaultTableModel) tblToken.getModel();
            int a =temp.getRowCount()-1;
            for(int i=-1; i<a; i++)
                temp.removeRow(0);
        }catch(Exception e){
            System.out.println(e);
            
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Analizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Analizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Analizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Analizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Analizador().setVisible(true);
            }
        });
    }

    private void inicializar(boolean enable) {
    }

    public void complementos() {
        this.repintarArbol();
    }
    
    public void verificar(String cad){
        txtEditor.setCaretPosition(0);
        txtEditor.setCaretColor(null);
        b=cad.charAt(cad.length()-1);
        if(b==';')
        {
            for(int a=0;a<cont;a++)
            {
                if(aux[a]=="" && aux[a+1]==""){
                    bandera=true;
                    showMessageDialog(null,"<html><center><font size='+2' color='BLACK'>USTED TIENE UN ERROR CERCA DE <font size='+3' color='red'>"+aux[a-1]+"</font></center></html>","",0);
                    limpiaTabla();
                    subrayar(txtEditor,aux[a-1].toString());
            }
        }
        }
        else{showMessageDialog(null,"<html><center><font size='+2' color='BLACK'>HACE FALTA UN <font size='+3' color='red'>"+";"+"</font></center></html>","",0);
        subrayar(txtEditor,aux[cont]+"");
        bandera=true;
        limpiaTabla();}
    }
    

    private void repintarArbol() {
        this.jDesktopPane1.removeAll();
        Rectangle tamaño = this.jInternalFrame2.getBounds();
        this.jInternalFrame2 = null;
        this.jInternalFrame2 = new JInternalFrame("Representación fráfica", true);
        this.jDesktopPane1.add(this.jInternalFrame2, JLayeredPane.DEFAULT_LAYER);
        this.jInternalFrame2.setVisible(true);
        this.jInternalFrame2.setBounds(tamaño);
        this.jInternalFrame2.setEnabled(false);
        this.jInternalFrame2.add(this.simulador.getDibujo(), BorderLayout.CENTER);
    }

    public void analizar(String cad) {
        String pal = "";
        cont=0;
        for(int a=0;a<20;a++)
            aux[a]="";
        bandera=false;
        m.setRowCount(0);
        Object O[] = new Object[2];
        cad = cad.replace(" ", "");
        for (int i = 1; i <=cad.length(); i++) {
            String c = cad.substring(i-1, i);
            if (esOp(c) == -1) {
                aux[cont]=aux[cont]+c;
                pal = pal + c;
            } else if (GrafosMio.esIde(pal)){
                O[0] = pal;
                 cont++;
                 O[1] = "Identificador";
                m.addRow(O);
                O[0] = c;
                O[1] = "Operador";
                m.addRow(O);
                pal = "";
                c = "";
            } else if (GrafosMio.esEntero(pal)) {
                O[0] = pal;
                 cont++;
                O[1] = "Entero";
                m.addRow(O);
                O[0] = c;
                O[1] = "Operador";
                m.addRow(O);
                pal = "";
                c = "";
            } else if (GrafosMio.esFloat(pal)){
                O[0] = pal;
                 cont++;
                O[1] = "Flotante";
                m.addRow(O);
                O[0] = c;
                O[1] = "Operador";
                m.addRow(O);
                pal = "";
                c = "";
            } else if (GrafosMio.esHex(pal)) {
                O[0] = pal;
                 cont++;
                O[1] = "Hexadecimal";
                m.addRow(O);
                O[0] = c;
                O[1] = "Operador";
                m.addRow(O);
                pal = "";
                c = "";
            }
        }
        verificar(cad);
    }

    private int esOp(String c) {
        for (int i = 0; i < OP.length; i++) {
            if (c.equals(OP[i])) {
                return i;
            }
        }
        return -1;
    }

    private DefaultTableModel m;
    private String OP[] = {"=", "+", "-", "*", "/", ";"};
    private String PR[] = {"Inicio", "Fin", "Desde", "If", "Mientras", "Sino"};
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ArbolBoton;
    private javax.swing.JButton Limpiar_Boton;
    private javax.swing.JButton btnAnalizar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem mnuAbrir;
    private javax.swing.JMenuItem mnuGuardar;
    private javax.swing.JMenuItem mnuNuevo;
    private javax.swing.JPanel pnlArbol;
    private javax.swing.JTable tblToken;
    private javax.swing.JTextArea txtEditor;
    // End of variables declaration//GEN-END:variables
}
